@echo off
echo Compiling Main class files...
javac -cp . main/Main.java -encoding utf8 -d bin
echo Compiling LangTest class files...
javac -cp . test/LangTest.java -encoding utf8 -d bin
cd bin
echo Creating Simulator.jar...
jar cvfe ../Simulator.jar main.Main .
echo Creating LangTest.jar...
jar cvfe ../LangTest.jar test.LangTest .
cd ..
echo Done.